import { afterAll, describe, expect, it } from 'vitest';
import { chromium, type Browser } from 'playwright';
import { createServer, type Server } from 'node:http';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { runCli, type CliIO } from '../../src/cli.js';
import { readAliasCatalog } from '../../src/projectWorkflow/aliasCatalog.js';
import { aliasCatalogPath, projectConfigPath, projectEvidenceRoot } from '../../src/projectWorkflow/projectPaths.js';
import { readObservationArtifact } from '../../src/artifacts/artifactReader.js';
import { approveAndPersistBaseline, persistPerChangeContract } from '../../src/application/frontendContractPersistenceService.js';
import { activateProjectVisualChangeWorkflow, createProjectVisualChangeWorkflow } from '../../src/application/visualChangeProjectWorkflowService.js';
import { persistAnnotationUnder, rectangleItem, runtimeSourceFor, TestResources } from '../support/annotationAuthoringFixtures.js';
import { startViewer, type StartViewerResult } from '../../src/viewerServer/viewerService.js';
import { readVisualChangeWorkflowArtifact } from '../../src/artifacts/visualChangeWorkflowArtifactReader.js';

const resources = new TestResources(); const servers: Server[] = []; let browser: Browser | undefined;
const output = (): CliIO => ({ stdout: () => undefined, stderr: () => undefined });
const page = (nav: number, workspace: number, rail: number) => `<!doctype html><style>html,body{margin:0}#nav{position:absolute;width:${nav}px;height:80px}#workspace{position:absolute;left:210px;width:${workspace}px;height:80px}#rail{position:absolute;left:800px;width:${rail}px;height:80px}</style><nav id="nav">Nav</nav><main id="workspace">Workspace</main><aside id="rail">Rail</aside>`;
async function server(root: string) { const instance = createServer(async (_req,res) => { res.writeHead(200, {'content-type':'text/html'}); res.end(await readFile(path.join(root,'source','index.html'))); }); await new Promise<void>((resolve) => instance.listen(0,'127.0.0.1',resolve)); servers.push(instance); const address=instance.address(); if (address===null||typeof address==='string') throw new Error('server'); return `http://127.0.0.1:${address.port}/`; }
async function cli(root: string, args: string[]) { const before=process.cwd(); process.chdir(root); try { return await runCli(args,output()); } finally { process.chdir(before); } }
async function workflowArtifacts(root: string) { const dir=path.join(projectEvidenceRoot(root),'visual-changes'); const ids=await readdir(dir); const artifacts=[]; for(const id of ids){ const read=await readVisualChangeWorkflowArtifact(path.join(dir,id,'manifest.json')); if(read.ok) artifacts.push(read.artifact); } return artifacts; }
afterAll(async()=>{ await browser?.close(); await Promise.all(servers.map((item)=>new Promise<void>((resolve)=>item.close(()=>resolve())))); await resources.cleanup(); });

describe('Batch 7 actual correction cycle', () => {
  it('ACCEPTANCE GATE: external FAIL edit requires review, correction produces a fresh PASS attempt, and acceptance is terminal', async () => {
    const root=await resources.tempDir('mfo-b7-actual-'); await mkdir(path.join(root,'source'),{recursive:true}); const source=path.join(root,'source','index.html'); await writeFile(source,page(200,500,150)); const url=await server(root);
    expect(await cli(root,['init','--url',url,'--viewport','1000x700','--target','nav=#nav','--target','workspace=#workspace','--target','rail=#rail'])).toBe(0); expect(await cli(root,['capture','baseline'])).toBe(0);
    const catalog=await readAliasCatalog(aliasCatalogPath(root)); if(!catalog.ok) throw new Error(catalog.reason); const record=catalog.catalog.observations.baseline!; const baselineRoot=path.join(projectEvidenceRoot(root),...record.relativeArtifactDir.split('/')); const observation=await readObservationArtifact(path.join(baselineRoot,'manifest.json')); if(!observation.ok) throw new Error(observation.reason);
    const baseline=await approveAndPersistBaseline({artifactKind:'my-frontend-observer/frontend-contract',schemaVersion:'1.0.0',contractClass:'baseline',baselineId:'b7-baseline',sourceObservation:{observationId:observation.artifact.observationId,requestId:observation.artifact.requestId,producer:observation.artifact.producer,observationSchemaVersion:observation.artifact.schemaVersion},clauses:[],provenance:{approvedAt:new Date(0).toISOString()}},baselineRoot,{outputLocation:'.frontend-observer/evidence/contracts',cwd:root}); if(!baseline.ok) throw new Error('baseline');
    const change=await persistPerChangeContract({artifactKind:'my-frontend-observer/frontend-contract',schemaVersion:'1.0.0',contractClass:'change',contractId:'b7-change',contractRequestId:'b7-change-request',activeBaselineIds:['b7-baseline'],clauses:[{clauseId:'requested-nav-shrink',primitive:{kind:'property-decreases',target:'nav',property:'width'},category:'requested',supportingEvidence:[]},{clauseId:'protected-rail-width',primitive:{kind:'property-unchanged-within-tolerance',target:'rail',property:'width',tolerance:{kind:'exact'}},category:'protected',supportingEvidence:[]}]},{outputLocation:'.frontend-observer/evidence/contracts',cwd:root}); if(!change.ok) throw new Error('change');
    const portable=(absolute:string)=>path.relative(root,absolute).split(path.sep).join('/'); const config=JSON.parse(await readFile(projectConfigPath(root),'utf8')); config.acceptance={contract:{baselineArtifact:portable(baseline.artifactRoot),changeArtifact:portable(change.artifactRoot)}}; await writeFile(projectConfigPath(root),`${JSON.stringify(config,null,2)}\n`);
    const annotation=await persistAnnotationUnder(projectEvidenceRoot(root),runtimeSourceFor(observation.artifact),[rectangleItem()]); const scope={entryMode:'actual-frontend' as const,annotationId:annotation.annotationId,annotationArtifactPath:portable(annotation.artifactRoot),baselineObservation:{artifactId:observation.artifact.observationId,observationId:observation.artifact.observationId,requestId:observation.artifact.requestId,artifactPath:portable(baselineRoot)},baselineContract:{artifactId:'b7-baseline',baselineId:'b7-baseline',artifactPath:portable(baseline.artifactRoot)},changeContract:{artifactId:'b7-change',contractId:'b7-change',contractRequestId:'b7-change-request',artifactPath:portable(change.artifactRoot)}};
    const created=await createProjectVisualChangeWorkflow({projectRoot:root,scope}); if(!created.ok) throw new Error('create'); const active=await activateProjectVisualChangeWorkflow({projectRoot:root,workflowManifestPath:portable(created.manifestPath)}); if(!active.ok) throw new Error('activate'); const activeBytes=await readFile(active.manifestPath); const requestId=active.visualChangeRequestId;
    const running=await startViewer({root:projectEvidenceRoot(root),port:0,assetsRoot:path.resolve(__dirname,'../../dist/viewer'),authoringProjectRoot:root}) as Extract<StartViewerResult,{ok:true}>; browser=browser??await chromium.launch(); const ui=await browser.newPage(); try { await ui.goto(running.url); await ui.getByRole('button',{name:'Visual changes'}).click(); const workflowButton=ui.locator('.visual-change-list button',{hasText:active.visualChangeWorkflowId}); await workflowButton.click(); await ui.getByRole('button',{name:'Prepare handoff'}).click(); await ui.locator('[data-handoff-ready="true"]').waitFor();
      await writeFile(source,page(140,500,130)); await ui.getByRole('button',{name:'Run check'}).click(); await expect.poll(async()=>await ui.locator('.visual-change-detail').textContent()).toContain('Latest checkFAIL'); expect(await ui.getByRole('button',{name:'Run check'}).isDisabled()).toBe(true); expect(await ui.getByRole('button',{name:'Prepare handoff'}).count()).toBe(0); expect(await ui.getByRole('button',{name:'Accept',exact:true}).isDisabled()).toBe(true); const first=(await workflowArtifacts(root)).find((item)=>item.attempts.length===1&&item.attempts[0]?.review.state==='pending'); if(first===undefined) throw new Error('first attempt'); expect(first.visualChangeRequestId).toBe(requestId); expect(first.attempts[0]?.check.status).toBe('FAIL'); expect(first.attempts[0]?.check.failedClauseIds).toContain('protected-rail-width');
      await ui.getByRole('button',{name:'Request correction'}).click(); await ui.getByText('Correction requested. Prepare a new handoff after making/planning the next external edit.').waitFor(); expect(await ui.getByRole('button',{name:'Run check'}).isDisabled()).toBe(false); await ui.getByRole('button',{name:'Prepare handoff'}).click(); await ui.locator('[data-handoff-ready="true"]').waitFor();
      await writeFile(source,page(195,500,150)); await ui.getByRole('button',{name:'Run check'}).click(); await expect.poll(async()=>await ui.locator('.visual-change-detail').textContent()).toContain('Latest checkPASS'); const second=(await workflowArtifacts(root)).find((item)=>item.attempts.length===2&&item.attempts[1]?.review.state==='pending'); if(second===undefined) throw new Error('second attempt'); expect(second.visualChangeRequestId).toBe(requestId); expect(second.attempts[1]?.priorVisualChangeAttemptId).toBe(second.attempts[0]?.visualChangeAttemptId); expect(second.attempts[1]?.candidateObservation.observationId).not.toBe(second.attempts[0]?.candidateObservation.observationId); expect(second.attempts[1]?.visualChangeAttemptId).not.toBe(second.attempts[0]?.visualChangeAttemptId); expect(second.attempts[0]?.review.state).toBe('correction-requested'); await ui.getByRole('button',{name:'Accept',exact:true}).click(); await expect.poll(async()=>await ui.locator('.visual-change-detail').textContent()).toContain('Accepted'); const accepted=(await workflowArtifacts(root)).find((item)=>item.attempts.length===2&&item.attempts[1]?.review.state==='accepted'); if(accepted===undefined) throw new Error('accepted'); expect(accepted.visualChangeRequestId).toBe(requestId); expect(accepted.governanceResults).toBeUndefined(); expect(await readFile(active.manifestPath)).toEqual(activeBytes); expect(await ui.getByRole('button',{name:'Run check'}).isDisabled()).toBe(true); expect(await ui.getByRole('button',{name:'Prepare handoff'}).count()).toBe(0); expect((await readFile(projectConfigPath(root),'utf8')).includes('b7-change')).toBe(true);
    } finally { await ui.close(); await running.close(); }
  },120_000);
});
