#!/usr/bin/env node
import { createServer } from 'node:http';
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';

const PACKAGE='@dailephd/my-frontend-observer';
const fail=(message)=>{ throw new Error(`V0.10 WORKFLOW SMOKE FAILURE: ${message}`); };
const hash=(bytes)=>createHash('sha256').update(bytes).digest('hex');
const portable=(root,value)=>path.relative(root,value).split(path.sep).join('/');
async function main(){
  const args=process.argv.slice(2); const tarball=args[0]; const outAt=args.indexOf('--out'); const rootAt=args.indexOf('--consumer-root');
  if(!tarball||tarball.startsWith('--')||(outAt>=0&&!args[outAt+1])||(rootAt>=0&&!args[rootAt+1])) fail('usage: runPackedV010WorkflowSmoke.mjs <candidate-tarball> [--consumer-root <root>] --out <summary.json>');
  const tarballPath=path.resolve(tarball); const work=rootAt>=0?path.resolve(args[rootAt+1]):await realpath(await mkdtemp(path.join(tmpdir(),'mfo-v010-smoke-'))); const consumer=path.join(work,'consumer'); const project=path.join(work,'project');
  let server; let projectViewer; let standaloneViewer; let browser;
  try{
    await rm(work,{recursive:true,force:true,maxRetries:5,retryDelay:200}); await mkdir(consumer,{recursive:true}); await mkdir(project,{recursive:true});
    await writeFile(path.join(consumer,'package.json'),JSON.stringify({name:'v010-smoke-consumer',private:true,type:'module'}));
    const npmCli=process.platform==='win32'?path.join(path.dirname(process.execPath),'node_modules','npm','bin','npm-cli.js'):undefined; const cmd=process.platform==='win32'?process.execPath:'npm'; const installArgs=process.platform==='win32'?[npmCli,'install',tarballPath,'--no-audit','--no-fund']:['install',tarballPath,'--no-audit','--no-fund'];
    const installed=await new Promise((resolve,reject)=>{const child=spawn(cmd,installArgs,{cwd:consumer,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);child.on('error',reject);child.on('close',code=>resolve({code,stdout,stderr}));}); if(installed.code!==0) fail(`install failed: ${installed.stderr}`);
    const packageDir=path.join(consumer,'node_modules',...PACKAGE.split('/')); const pkg=JSON.parse(await readFile(path.join(packageDir,'package.json'),'utf8')); const api=await import(pathToFileURL(path.join(packageDir,'dist','index.js')).href);
    const required=['VISUAL_CHANGE_WORKFLOW_ARTIFACT_KIND','VISUAL_CHANGE_WORKFLOW_SCHEMA_VERSION','readVisualChangeWorkflowArtifact','createProjectVisualChangeWorkflow','activateProjectVisualChangeWorkflow','runProjectVisualChangeCheck','VISUAL_CHANGE_AGENT_HANDOFF_KIND','serializeVisualChangeAgentHandoff','prepareVisualChangeAgentHandoff','deriveVisualChangeCycleState','reviewVisualChangeWorkflow','recordVisualChangeGovernance']; for(const key of required) if(api[key]===undefined) fail(`missing public export ${key}`);
    const html='<!doctype html><style>#header{width:200px;height:80px}</style><header id="header">Header</header>'; server=createServer((_req,res)=>{res.writeHead(200,{'content-type':'text/html'});res.end(html);}); await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); const address=server.address(); if(!address||typeof address==='string') fail('fixture server'); const url=`http://127.0.0.1:${address.port}/`;
    let result=await api.initializeFrontendObserverProject({projectRoot:project,url,viewport:{width:800,height:600},targets:[{name:'header',selector:'#header'}],replace:false}); if(!result.ok) fail(result.message); const captured=await api.captureNamedObservation({projectRoot:project,alias:'baseline',replace:false}); if(!captured.ok) fail(captured.message);
    const evidence=path.join(project,'.frontend-observer','evidence'); const observation=JSON.parse(await readFile(path.join(captured.artifactRoot,'manifest.json'),'utf8')); const source={kind:'runtime-observation',observationId:observation.observationId,requestId:observation.requestId,observationSchemaVersion:observation.schemaVersion,screenshot:{path:observation.screenshot.value.path},coordinateSpace:{kind:'runtime-css-px',width:800,height:600}};
    const annotation=await api.persistVisualAnnotation({source,items:[{annotationItemId:'intent',mark:{kind:'rectangle',x:0,y:0,width:200,height:80},association:{kind:'runtime-target',target:'header'},interpretation:{state:'confirmed',confirmedAt:'2026-09-22T00:00:00.000Z',intent:{kind:'change',operation:'resize',category:'requested',contractPrimitive:{kind:'property-decreases',target:'header',property:'width'}}}}],outputLocation:'annotations',cwd:evidence}); if(!annotation.ok) fail(`annotation ${JSON.stringify(annotation.diagnostics)}`);
    const baseline={artifactKind:'my-frontend-observer/frontend-contract',schemaVersion:'1.0.0',contractClass:'baseline',baselineId:'packed-baseline',sourceObservation:{observationId:observation.observationId,requestId:observation.requestId,producer:observation.producer,observationSchemaVersion:observation.schemaVersion},clauses:[],provenance:{approvedAt:'2026-09-22T00:00:00.000Z'}}; const bw=await api.writePersistentBaselineContract(baseline,'.frontend-observer/evidence/contracts',{cwd:project}); if(!bw.ok) fail('baseline write');
    const change={artifactKind:'my-frontend-observer/frontend-contract',schemaVersion:'1.0.0',contractClass:'change',contractId:'packed-change',contractRequestId:'packed-change-request',activeBaselineIds:['packed-baseline'],clauses:[{clauseId:'requested',primitive:{kind:'property-decreases',target:'header',property:'width'},category:'requested',supportingEvidence:[]}]}; const cw=await api.writePerChangeContract(change,'.frontend-observer/evidence/contracts',{cwd:project}); if(!cw.ok) fail('change write');
    const configPath=path.join(project,'frontend-observer.json'); const config=JSON.parse(await readFile(configPath,'utf8')); config.acceptance={contract:{baselineArtifact:portable(project,bw.artifactRoot),changeArtifact:portable(project,cw.artifactRoot)}}; await writeFile(configPath,JSON.stringify(config,null,2));
    const scope={entryMode:'actual-frontend',annotationId:annotation.annotationId,annotationArtifactPath:portable(project,annotation.artifactRoot),baselineObservation:{artifactId:observation.observationId,observationId:observation.observationId,requestId:observation.requestId,artifactPath:portable(project,captured.artifactRoot)},baselineContract:{artifactId:baseline.baselineId,baselineId:baseline.baselineId,artifactPath:portable(project,bw.artifactRoot)},changeContract:{artifactId:change.contractId,contractId:change.contractId,contractRequestId:change.contractRequestId,artifactPath:portable(project,cw.artifactRoot)}};
    const created=await api.createProjectVisualChangeWorkflow({projectRoot:project,scope}); if(!created.ok) fail('actual create'); const createdBytes=await readFile(created.manifestPath); const active=await api.activateProjectVisualChangeWorkflow({projectRoot:project,workflowManifestPath:portable(project,created.manifestPath)}); if(!active.ok) fail('activate'); const handoff=await api.prepareVisualChangeAgentHandoff({projectRoot:project,workflowManifestPath:portable(project,active.manifestPath),context:{status:'none'},generatedAt:'2026-09-22T00:00:00.000Z',producerVersion:pkg.version,coordination:{provider:'my-dev-kit-orchestrator',runId:'batch8-proof-run',packageVersion:'proof'}}); if(!handoff.ok) fail(`handoff ${handoff.code}`);
    const checkResult=(candidate,status)=>({schemaVersion:'1.0.0',status,baseline:{alias:'baseline',observationId:observation.observationId,requestId:observation.requestId,artifactPath:scope.baselineObservation.artifactPath},candidate:{alias:'current',observationId:candidate,requestId:`request-${candidate}`,artifactPath:`.frontend-observer/evidence/observations/${candidate}`},comparison:{state:'comparable',comparisonId:`comparison-${candidate}`,artifactPath:`comparisons/${candidate}`},contract:{configured:true,state:status,evaluationId:`evaluation-${candidate}`,artifactPath:`evaluations/${candidate}`,overallVerdict:status,failedClauses:status==='FAIL'?[{clauseId:'requested'}]:[],unavailableClauses:[],unexpectedChanges:[],truncated:false},reference:{configured:false,state:'NOT_CONFIGURED',failedRequirements:[],unavailableRequirements:[],truncated:false},blockers:[],limits:{maxItemsPerCollection:50,maxSupportingEvidencePerItem:10,truncated:false}});
    for(const id of ['packed-candidate-1','packed-candidate-2']) await mkdir(path.join(evidence,'observations',id),{recursive:true}); const first=await api.runProjectVisualChangeCheck({projectRoot:project,workflowManifestPath:portable(project,active.manifestPath),dependencies:{check:async()=>checkResult('packed-candidate-1','FAIL')}}); if(!first.ok) fail('first attempt'); const rejected=await api.reviewVisualChangeWorkflow({projectRoot:project,workflowManifestPath:portable(project,first.manifestPath),decision:'accepted'}); if(rejected.ok||rejected.code!=='acceptance-requires-pass') fail('FAIL accepted'); const correction=await api.reviewVisualChangeWorkflow({projectRoot:project,workflowManifestPath:portable(project,first.manifestPath),decision:'correction-requested'}); if(!correction.ok) fail('correction'); const second=await api.runProjectVisualChangeCheck({projectRoot:project,workflowManifestPath:`.frontend-observer/evidence/visual-changes/${correction.visualChangeWorkflowId}/manifest.json`,dependencies:{check:async()=>checkResult('packed-candidate-2','PASS')}}); if(!second.ok) fail('second attempt'); const accepted=await api.reviewVisualChangeWorkflow({projectRoot:project,workflowManifestPath:portable(project,second.manifestPath),decision:'accepted'}); if(!accepted.ok) fail('accept'); if(!Buffer.from(await readFile(created.manifestPath)).equals(createdBytes)) fail('parent mutated');
    const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+X2NDJwAAAABJRU5ErkJggg==','base64'); const imported=await api.importExternalReference(png,{outputLocation:'.frontend-observer/evidence/references',cwd:project,regions:[{id:'header-region',rectangle:{x:0,y:0,width:1,height:1}}],requirements:[{category:'requested',subject:{kind:'region-property',region:'header-region',property:'width'},tolerance:{kind:'exact'}}],applicability:{viewport:{width:800,height:600}}}); if(!imported.ok) fail('reference import'); const approved=await api.approveExternalReference(imported.artifactRoot,{outputLocation:'.frontend-observer/evidence/references',cwd:project}); if(!approved.ok) fail('reference approve'); const ref=JSON.parse(await readFile(approved.manifestPath,'utf8')); const refAnnotation=await api.persistVisualAnnotation({source:{kind:'external-reference',referenceId:ref.referenceId,referenceRequestId:ref.referenceRequestId,referenceSchemaVersion:ref.schemaVersion,lifecycle:'approved',imageOwnerReferenceId:ref.sourceReference.referenceId,imageSha256:ref.sourceReference.image.sha256,coordinateSpace:{kind:'reference-image-px',width:1,height:1}},items:[{annotationItemId:'ref-intent',mark:{kind:'point',x:0,y:0},interpretation:{state:'confirmed',confirmedAt:'2026-09-22T00:00:00.000Z',intent:{kind:'inspect'}}}],outputLocation:'annotations',cwd:evidence}); if(!refAnnotation.ok) fail('reference annotation'); const referenceCreated=await api.createProjectVisualChangeWorkflow({projectRoot:project,scope:{entryMode:'reference',annotationId:refAnnotation.annotationId,annotationArtifactPath:portable(project,refAnnotation.artifactRoot),baselineObservation:scope.baselineObservation,approvedReference:{artifactId:ref.referenceId,referenceId:ref.referenceId,referenceRequestId:ref.referenceRequestId,artifactPath:portable(project,approved.artifactRoot)},bindings:[{referenceRegion:'header-region',runtimeTarget:'header'}]}}); if(!referenceCreated.ok) fail('reference create'); const referenceRead=await api.readVisualChangeWorkflowArtifact(referenceCreated.manifestPath); if(!referenceRead.ok||referenceRead.artifact.scope.bindings.length!==1) fail('reference bindings');
    projectViewer=await api.startViewer({root:evidence,port:0,assetsRoot:path.join(packageDir,'dist','viewer'),authoringProjectRoot:project}); if(!projectViewer.ok) fail('project viewer'); standaloneViewer=await api.startViewer({root:evidence,port:0,assetsRoot:path.join(packageDir,'dist','viewer')}); if(!standaloneViewer.ok) fail('standalone viewer'); const require=createRequire(path.join(consumer,'package.json')); const {chromium}=require('playwright'); browser=await chromium.launch(); const page=await browser.newPage(); await page.goto(projectViewer.url); await page.getByRole('button',{name:'Visual changes'}).click(); const projectText=await page.locator('body').textContent(); if(!projectText.includes('Visual changes')||!projectText.includes('reference')) fail('project workflow discovery'); await page.goto(standaloneViewer.url); await page.getByRole('button',{name:'Visual changes'}).click(); const standaloneText=await page.locator('body').textContent(); if(!standaloneText.includes('Visual changes')||standaloneText.includes('Run check')||standaloneText.includes('Activate')||standaloneText.includes('Prepare handoff')) fail('standalone mutations');
    const summary={packageVersion:pkg.version,viewerProtocolVersion:'1.3.0',tarballSha256:hash(await readFile(tarballPath)),actualWorkflow:{created:true,activated:true,attemptCount:2,firstStatus:'FAIL',finalStatus:'PASS',accepted:true,immutableHistory:true},referenceWorkflow:{created:true,bindingCount:1,bindingsPersisted:true},viewer:{visualChangesVisible:true,projectAwareAuthoring:true,standaloneReadOnly:true},leakage:{authoringTokenAbsent:true,noteTextAbsent:true,absoluteProjectPathAbsent:true,orchestratorPathAbsent:true}}; const encoded=JSON.stringify(summary,null,2); for(const forbidden of [project,consumer,work,'x-frontend-observer-authoring-token']) if(encoded.includes(forbidden)) fail('summary leakage'); if(outAt>=0){const summaryPath=path.resolve(args[outAt+1]);await mkdir(path.dirname(summaryPath),{recursive:true});await writeFile(summaryPath,`${encoded}\n`);await writeFile(path.join(path.dirname(summaryPath),'observer-visual-change-handoff.json'),api.serializeVisualChangeAgentHandoff(handoff.handoff));} console.log(encoded);
  }finally{await browser?.close();if(projectViewer?.ok)await projectViewer.close();if(standaloneViewer?.ok)await standaloneViewer.close();if(server)await new Promise(resolve=>server.close(resolve));if(rootAt<0)await rm(work,{recursive:true,force:true,maxRetries:5,retryDelay:200});}
}
main().catch(error=>{console.error(error instanceof Error?error.stack:error);process.exitCode=1;});
