import { useEffect, useState } from 'react';

export type VisualChangeViewState = { state: 'idle'|'loading' } | { state: 'available'; view: VisualChangeView } | { state: 'error'; message: string };
export interface LinkedWorkflowEvidence { status: 'available'|'unavailable'; handle?: string; family?: string; reason?: string }
export interface VisualChangeAttempt { visualChangeAttemptId: string; candidateObservation: { observationId: string }; check: { status: string; referenceFidelityState?: string; failedClauseIds: string[]; unavailableClauseIds: string[]; failedReferenceRequirementIds: string[]; unavailableReferenceRequirementIds: string[]; unexpectedChangeCount: number; blockerCodes: string[] }; review: { state: string; decidedAt?: string }; recordedAt: string }
export interface VisualChangeWorkflow { visualChangeRequestId: string; visualChangeWorkflowId: string; supersedesVisualChangeWorkflowId?: string; scope: { entryMode: 'actual-frontend'|'reference'; annotationId: string; baselineObservation: { observationId: string }; changeContract?: { contractId: string }; approvedReference?: { referenceId: string } }; attempts: VisualChangeAttempt[]; activation?: { restoredAt?: string }; governanceResults?: { baselineApproval?: { artifactId: string }; externalReferenceApproval?: { artifactId: string } } }
export interface VisualChangeView { workflow: VisualChangeWorkflow; baselineObservation: LinkedWorkflowEvidence; annotation: LinkedWorkflowEvidence; changeContract?: LinkedWorkflowEvidence; baselineContract?: LinkedWorkflowEvidence; approvedReference?: LinkedWorkflowEvidence; attempts: Array<{ candidateObservation: LinkedWorkflowEvidence; comparison?: LinkedWorkflowEvidence; contractEvaluation?: LinkedWorkflowEvidence }> }
export function useVisualChangeView(handle: string | undefined): VisualChangeViewState {
  const [state, setState] = useState<VisualChangeViewState>({ state: 'idle' });
  useEffect(() => { const controller = new AbortController(); if (handle === undefined) { setState({ state: 'idle' }); return () => controller.abort(); } setState({ state: 'loading' }); void (async () => { try { const response = await fetch(`/api/visual-changes/${encodeURIComponent(handle)}/view`, { cache: 'no-store', signal: controller.signal }); const body = (await response.json()) as { ok?: boolean; view?: VisualChangeView; error?: string }; if (!controller.signal.aborted) setState(response.ok && body.ok === true && body.view !== undefined ? { state: 'available', view: body.view } : { state: 'error', message: body.error ?? `workflow view failed with status ${response.status}` }); } catch (error) { if (!controller.signal.aborted) setState({ state: 'error', message: error instanceof Error ? error.message : String(error) }); } })(); return () => controller.abort(); }, [handle]);
  return state;
}
