import { useState } from 'react';
import type { AuthoringSessionState } from '../hooks/useAuthoringSession.js';
import type { EvidenceIndexState, EvidenceMetadataRecord } from '../hooks/useEvidenceIndex.js';
import { useVisualChangeView, type LinkedWorkflowEvidence, type VisualChangeAttempt } from '../hooks/useVisualChangeView.js';
import { useVisualChangeActions } from '../hooks/useVisualChangeActions.js';

interface Props { index: EvidenceIndexState; authoring: AuthoringSessionState; refresh: () => Promise<EvidenceIndexState>; onNavigate: (record: EvidenceMetadataRecord) => void }
function EvidenceLink({ label, evidence, records, onNavigate }: { label: string; evidence: LinkedWorkflowEvidence; records: EvidenceMetadataRecord[]; onNavigate: (record: EvidenceMetadataRecord) => void }) {
  if (evidence.status !== 'available' || evidence.handle === undefined) return <li>{label}: unavailable — {evidence.reason ?? 'exact linked evidence is unavailable'}</li>;
  const record = records.find((item) => item.handle === evidence.handle); return <li>{label}: {record === undefined ? 'available' : <button type="button" onClick={() => onNavigate(record)}>{evidence.family}</button>}</li>;
}
export function VisualChangeWorkspace({ index, authoring, refresh, onNavigate }: Props) {
  const records = index.state === 'available' ? index.records.filter((record) => record.family === 'visual-change-workflow') : [];
  const [selected, setSelected] = useState<EvidenceMetadataRecord>(); const [warning, setWarning] = useState<string>();
  const view = useVisualChangeView(selected?.handle); const actions = useVisualChangeActions(selected?.handle);
  const availableView = view.state === 'available' ? view.view : undefined;
  async function mutate(action: 'activate'|'check'|'restore-acceptance') { if (authoring.state !== 'available') return; const id = await actions.run(action, authoring.token); if (id === undefined) return; const next = await refresh(); if (next.state !== 'available') { setWarning('The evidence index could not be refreshed after the operation.'); return; } const exact = next.records.find((record) => record.family === 'visual-change-workflow' && record.supportState === 'supported' && record.logicalId === id); if (exact === undefined) { setWarning('The new immutable workflow revision was not found after refresh.'); return; } setWarning(undefined); setSelected(exact); }
  const workflow = availableView?.workflow; const active = workflow?.activation !== undefined && workflow.activation.restoredAt === undefined;
  return <section className="visual-change-workspace" aria-label="Visual changes">
    <aside><h2>Visual changes</h2>{records.length === 0 ? <p>No visual-change workflows found.</p> : <ul className="visual-change-list">{records.map((record) => <li key={record.handle}><button type="button" aria-pressed={selected?.handle === record.handle} onClick={() => { setSelected(record); setWarning(undefined); }}>{record.visualChangeEntryMode ?? 'workflow'} · {record.logicalId}</button></li>)}</ul>}</aside>
    <div className="visual-change-detail">{selected === undefined ? <p>Select a workflow to inspect it.</p> : view.state === 'loading' ? <p>Loading workflow…</p> : view.state === 'error' ? <p role="alert">{view.message}</p> : workflow === undefined ? null : <>
      <h2>Workflow summary</h2><dl><dt>Entry mode</dt><dd>{workflow.scope.entryMode}</dd><dt>Request ID</dt><dd>{workflow.visualChangeRequestId}</dd><dt>Workflow ID</dt><dd>{workflow.visualChangeWorkflowId}</dd>{workflow.supersedesVisualChangeWorkflowId && <><dt>Supersedes</dt><dd>{workflow.supersedesVisualChangeWorkflowId}</dd></>}<dt>Baseline observation</dt><dd>{workflow.scope.baselineObservation.observationId}</dd><dt>Annotation</dt><dd>{workflow.scope.annotationId}</dd><dt>{workflow.scope.entryMode === 'actual-frontend' ? 'Change contract' : 'Approved reference'}</dt><dd>{workflow.scope.entryMode === 'actual-frontend' ? workflow.scope.changeContract?.contractId : workflow.scope.approvedReference?.referenceId}</dd><dt>Attempts</dt><dd>{workflow.attempts.length}</dd><dt>Activation</dt><dd>{workflow.activation === undefined ? 'not activated' : active ? 'active' : 'restored'}</dd><dt>Latest check</dt><dd>{workflow.attempts.at(-1)?.check.status ?? 'none'}</dd><dt>Latest review</dt><dd>{workflow.attempts.at(-1)?.review.state ?? 'none'}</dd></dl>
      {authoring.state === 'available' ? <div className="visual-change-actions"><button type="button" disabled={workflow.activation !== undefined || actions.state.state === 'pending'} onClick={() => void mutate('activate')}>Activate</button><button type="button" disabled={!active || actions.state.state === 'pending'} onClick={() => void mutate('check')}>{actions.state.state === 'pending' && actions.state.action === 'check' ? 'Running check…' : 'Run check'}</button><button type="button" disabled={!active || actions.state.state === 'pending'} onClick={() => void mutate('restore-acceptance')}>Restore acceptance</button></div> : <p>{authoring.state === 'error' ? authoring.message : 'Project-aware authoring is required to modify visual-change workflow state.'}</p>}
      <div aria-live="polite" role="status">{actions.state.state === 'failed' ? actions.state.message : actions.state.state === 'success' ? 'Workflow operation completed.' : warning}</div>
      {availableView && <><h3>Linked evidence</h3><ul><EvidenceLink label="Baseline" evidence={availableView.baselineObservation} records={index.state === 'available' ? index.records : []} onNavigate={onNavigate}/><EvidenceLink label="Annotation" evidence={availableView.annotation} records={index.state === 'available' ? index.records : []} onNavigate={onNavigate}/>{availableView.changeContract && <EvidenceLink label="Change contract" evidence={availableView.changeContract} records={index.state === 'available' ? index.records : []} onNavigate={onNavigate}/>} {availableView.approvedReference && <EvidenceLink label="Approved reference" evidence={availableView.approvedReference} records={index.state === 'available' ? index.records : []} onNavigate={onNavigate}/>}</ul></>}
      <h3>Attempt timeline</h3>{workflow.attempts.length === 0 ? <p>No attempts recorded.</p> : <ol className="attempt-timeline">{workflow.attempts.map((attempt: VisualChangeAttempt, i: number) => <li key={attempt.visualChangeAttemptId}><h4>Attempt {i + 1}</h4><dl><dt>Attempt ID</dt><dd>{attempt.visualChangeAttemptId}</dd><dt>Candidate</dt><dd>{attempt.candidateObservation.observationId}</dd><dt>Status</dt><dd>{attempt.check.status}</dd>{attempt.check.referenceFidelityState && <><dt>Reference fidelity</dt><dd>{attempt.check.referenceFidelityState}</dd></>}<dt>Failed clauses</dt><dd>{attempt.check.failedClauseIds.length}</dd><dt>Unavailable clauses</dt><dd>{attempt.check.unavailableClauseIds.length}</dd><dt>Failed reference requirements</dt><dd>{attempt.check.failedReferenceRequirementIds.length}</dd><dt>Unavailable reference requirements</dt><dd>{attempt.check.unavailableReferenceRequirementIds.length}</dd><dt>Unexpected changes</dt><dd>{attempt.check.unexpectedChangeCount}</dd><dt>Blockers</dt><dd>{attempt.check.blockerCodes.length}</dd><dt>Review</dt><dd>{attempt.review.state}</dd><dt>Recorded</dt><dd>{attempt.recordedAt}</dd></dl></li>)}</ol>}</> }</div>
  </section>;
}
