import { afterEach, describe, expect, it, vi } from 'vitest';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { writePersistentBaselineContract } from '../../src/artifacts/frontendContractArtifactWriter.js';
import { readPerChangeContract } from '../../src/artifacts/frontendContractArtifactReader.js';
import { readVisualChangeWorkflowArtifact } from '../../src/artifacts/visualChangeWorkflowArtifactReader.js';
import { writeAliasCatalog, ALIAS_CATALOG_SCHEMA_VERSION } from '../../src/projectWorkflow/aliasCatalog.js';
import { aliasCatalogPath, projectConfigPath, projectContractsRoot, projectEvidenceRoot, projectVisualChangesRoot } from '../../src/projectWorkflow/projectPaths.js';
import { encodeArtifactHandle } from '../../src/viewerServer/evidence/handles.js';
import { startRuntimeVisualChangeFromViewer } from '../../src/viewerServer/runtimeVisualChangeAuthoring.js';
import { promoteVisualAnnotationContract } from '../../src/application/visualAnnotationContractPromotionService.js';
import { createProjectVisualChangeWorkflow } from '../../src/application/visualChangeProjectWorkflowService.js';
import type { VisualAnnotationItem } from '../../src/domain/visualAnnotation.js';
import { buildBaselineContract } from '../support/evidenceFixtures.js';
import { TestResources, authoringHeaders, fetchAuthoringToken, persistAnnotationUnder, rawRequest, referenceSourceFor, runtimeSourceFor, writeInitializedProject } from '../support/annotationAuthoringFixtures.js';

const resources = new TestResources(); afterEach(() => resources.cleanup());
const association = { kind: 'runtime-target' as const, target: 'header' };
const confirmed = (id: string, intent: Extract<VisualAnnotationItem['interpretation'], { state: 'confirmed' }>['intent'], withAssociation = true): VisualAnnotationItem => ({ annotationItemId: id, mark: { kind: 'rectangle', x: 1, y: 1, width: 10, height: 10 }, ...(withAssociation ? { association } : {}), interpretation: { state: 'confirmed', intent, confirmedAt: '2026-09-22T00:00:00.000Z' } });
const items: VisualAnnotationItem[] = [confirmed('move', { kind: 'change', operation: 'move', category: 'requested', contractPrimitive: { kind: 'property-increases', target: 'header', property: 'x' } }), confirmed('preserve', { kind: 'change', operation: 'preserve', category: 'preserved', contractPrimitive: { kind: 'property-unchanged-within-tolerance', target: 'header', property: 'width', tolerance: { kind: 'exact' } } }), confirmed('remove', { kind: 'change', operation: 'remove', category: 'requested' }), confirmed('inspect', { kind: 'inspect' }, false)];

async function context(configure = true) {
  const project = await writeInitializedProject(resources); project.observation.requestId = 'a'.repeat(64); project.observation.observationId = `${'b'.repeat(64)}-${'c'.repeat(32)}`; await writeFile(path.join(project.observationRoot, 'manifest.json'), `${JSON.stringify(project.observation, null, 2)}\n`);
  const saved = await persistAnnotationUnder(project.root, runtimeSourceFor(project.observation), items);
  await writeAliasCatalog(aliasCatalogPath(project.projectRoot), { schemaVersion: ALIAS_CATALOG_SCHEMA_VERSION, observations: { runtime: { observationId: project.observation.observationId, requestId: project.observation.requestId, relativeArtifactDir: path.relative(projectEvidenceRoot(project.projectRoot), project.observationRoot).split(path.sep).join('/') } } });
  if (configure) { const baseline = buildBaselineContract({ baselineId: 'visual-change-baseline' }); const written = await writePersistentBaselineContract(baseline, '.frontend-observer/evidence/baselines', { cwd: project.projectRoot }); if (!written.ok) throw new Error('baseline'); const config = JSON.parse(await readFile(projectConfigPath(project.projectRoot), 'utf8')) as Record<string, unknown>; const baselineArtifact = path.relative(project.projectRoot, written.artifactRoot).split(path.sep).join('/'); await writeFile(projectConfigPath(project.projectRoot), `${JSON.stringify({ ...config, acceptance: { contract: { baselineArtifact, changeArtifact: '.frontend-observer/evidence/contracts/previous' } } }, null, 2)}\n`); }
  const viewer = await resources.startViewer({ root: project.root, authoringProjectRoot: project.projectRoot }); const token = await fetchAuthoringToken(viewer); return { project, viewer, token, saved, handle: encodeArtifactHandle('visual-annotation', saved.relativeDir) };
}
async function start(ctx: Awaited<ReturnType<typeof context>>, itemIds: string[], extra: Record<string, unknown> = {}, handle = ctx.handle) { const body = JSON.stringify({ itemIds, ...extra }); const response = await rawRequest(ctx.viewer, { method: 'POST', path: `/api/annotations/${encodeURIComponent(handle)}/start-visual-change`, headers: authoringHeaders(ctx.viewer, ctx.token, body), body }); return { ...response, json: JSON.parse(response.text) as Record<string, unknown> }; }

describe('actual-frontend visual-change start route', () => {
  it('promotes only selected executable intent, keeps mixed remove/inspect evidence, creates an inactive exact workflow, and leaves acceptance unchanged', async () => {
    const ctx = await context(); const before = await readFile(projectConfigPath(ctx.project.projectRoot), 'utf8'); const result = await start(ctx, ['preserve', 'move']); expect(result.status).toBe(201); expect(result.json.clauseCount).toBe(2); expect(result.text).not.toContain(ctx.project.projectRoot); expect(await readFile(projectConfigPath(ctx.project.projectRoot), 'utf8')).toBe(before);
    const contract = await readPerChangeContract(path.join(projectContractsRoot(ctx.project.projectRoot), result.json.contractId as string, 'manifest.json')); if (!contract.ok) throw new Error(contract.reason); expect(contract.contract.clauses.map((clause) => clause.primitive.kind)).toEqual(['property-unchanged-within-tolerance','property-increases']);
    const workflows = await readdir(projectVisualChangesRoot(ctx.project.projectRoot)); const workflow = await readVisualChangeWorkflowArtifact(path.join(projectVisualChangesRoot(ctx.project.projectRoot), workflows[0]!, 'manifest.json')); if (!workflow.ok) throw new Error(workflow.reason); expect(workflow.artifact).toMatchObject({ scope: { entryMode: 'actual-frontend', annotationId: ctx.saved.annotationId, baselineObservation: { observationId: ctx.project.observation.observationId }, changeContract: { contractId: result.json.contractId } }, attempts: [] }); expect(workflow.artifact.activation).toBeUndefined(); expect(workflow.artifact.governanceResults).toBeUndefined();
  });
  it('validates prerequisites and selected intent before writing a contract', async () => { const ctx = await context(false); expect((await start(ctx, ['move'])).status).toBe(409); expect(await readdir(projectContractsRoot(ctx.project.projectRoot)).catch(() => [])).toEqual([]); const configured = await context(); for (const ids of [[], ['remove'], ['inspect']]) expect((await start(configured, ids)).status).toBe(ids.length === 0 ? 400 : 422); expect((await start(configured, ['move'], { activateForCheck: true })).status).toBe(400); });
  it('repeated equivalent starts retain contract request equivalence but create fresh contract/workflow request instances', async () => { const ctx = await context(); const before = await readFile(projectConfigPath(ctx.project.projectRoot), 'utf8'); const first = await start(ctx, ['move']); const second = await start(ctx, ['move']); expect(first.status).toBe(201); expect(second.status).toBe(201); expect(second.json.contractRequestId).toBe(first.json.contractRequestId); expect(second.json.contractId).not.toBe(first.json.contractId); expect(second.json.visualChangeRequestId).not.toBe(first.json.visualChangeRequestId); expect(second.json.visualChangeWorkflowId).not.toBe(first.json.visualChangeWorkflowId); expect(await readFile(projectConfigPath(ctx.project.projectRoot), 'utf8')).toBe(before); expect((await readdir(projectContractsRoot(ctx.project.projectRoot))).length).toBe(2); });
  it('changes request identity for a saved annotation revision and contract/request identity for changed executable intent', async () => { const ctx = await context(); const first = await start(ctx, ['move']); const revision = await persistAnnotationUnder(ctx.project.root, runtimeSourceFor(ctx.project.observation), items, ctx.saved.annotationId); const revised = await start(ctx, ['move'], {}, encodeArtifactHandle('visual-annotation', revision.relativeDir)); const changed = await start(ctx, ['preserve']); expect(revised.json.visualChangeRequestId).not.toBe(first.json.visualChangeRequestId); expect(changed.json.contractRequestId).not.toBe(first.json.contractRequestId); expect(changed.json.visualChangeRequestId).not.toBe(first.json.visualChangeRequestId); });
  it('calls canonical promotion once and reports retained contract identity when workflow creation fails', async () => { const ctx = await context(); const promote = vi.fn(promoteVisualAnnotationContract); const create = vi.fn(async () => ({ ok: false as const, code: 'workflow-persistence-failure' as const, reason: 'injected' })); const result = await startRuntimeVisualChangeFromViewer(ctx.project.root, { projectRoot: ctx.project.projectRoot, token: 'a'.repeat(64), expectedHost: '127.0.0.1:1', expectedOrigin: 'http://127.0.0.1:1' }, ctx.handle, { itemIds: ['move'] }, { promote, create: create as typeof createProjectVisualChangeWorkflow }); expect(promote).toHaveBeenCalledTimes(1); expect(create).toHaveBeenCalledTimes(1); expect(result).toMatchObject({ ok: false, reason: 'workflow-persistence-failed', contractId: expect.any(String), contractRequestId: expect.any(String) }); expect((await readdir(projectContractsRoot(ctx.project.projectRoot))).length).toBe(1); });
  it('rejects unknown/reference handles and standalone/security failures', async () => { const ctx = await context(); expect((await start(ctx, ['move'], {}, 'visual-annotation:annotations%2Fmissing')).status).toBe(404); const ref = await persistAnnotationUnder(ctx.project.root, referenceSourceFor(ctx.project.imported), [confirmed('inspect-ref', { kind: 'inspect' }, false)]); expect((await start(ctx, ['inspect-ref'], {}, encodeArtifactHandle('visual-annotation', ref.relativeDir))).status).toBe(409); const standalone = await resources.startViewer({ root: ctx.project.root }); const body = JSON.stringify({ itemIds: ['move'] }); expect((await rawRequest(standalone, { method: 'POST', path: `/api/annotations/${encodeURIComponent(ctx.handle)}/start-visual-change`, headers: { 'content-type': 'application/json' }, body })).status).toBe(403); expect((await rawRequest(ctx.viewer, { method: 'POST', path: `/api/annotations/${encodeURIComponent(ctx.handle)}/start-visual-change`, headers: { ...authoringHeaders(ctx.viewer, ctx.token, body), origin: 'http://evil.example' }, body })).status).toBe(403); });
});
